# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Dr. Philcsar's Phys-Math Tutorials
# Description of the Site
description: Your guide to physics and math
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: drphilcsar, physics tutorial, math tutorial, philippines
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: drphilcsar@gmail.com
facebook_username: drphilcsar1
twitter_username: DrPhilCsar
# instagram_username: thedevslot
# linkedin_username: thedevslot
# github_username:  thedevslot
youtube_channel_id: UCQZBy6wWX3we3LcENoUfVfA
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: drphilcsar

# Name of the Author
author-name: Philip Caesar Flores, PhD
# URL for the Image of the Author
author-image: /assets/images/caricature.jpg
# 60 Words About the Author
author-about: Welcome to "Dr. Philcsar's Phys-Math Tutorials" YouTube channel! Our mission is to inspire and empower Filipino students to pursue exciting careers in physics by providing engaging and comprehensive tutorials. We believe that everyone has the potential to excel in these subjects, and we're here to guide you every step of the way. Whether you're a high school student preparing for college entrance exams or a college student diving into advanced concepts, our channel is your go-to resource. We offer clear explanations, practical examples, and problem-solving strategies to help you master physics and math. Through our tutorials, we aim to demystify complex topics, making them accessible and enjoyable for all. We understand the challenges that Filipino students face in their academic journey, and we're committed to providing tailored content that addresses those specific needs. Our video library covers a wide range of subjects, including algebra, geometry, calculus, mechanics, and more. We break down each concept into digestible pieces, guiding you through the fundamental principles and building your knowledge from the ground up. Additionally, we offer tips and tricks to tackle challenging problems and enhance your problem-solving skills.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://philcsar2.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
